flyway:
  baseline-version: 0
  out-of-order: true
spring:
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "root"
    password: "password"
    url: "jdbc:mariadb://localhost:3306/iti0208"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jooq:
    sql-dialect: "MARIADB"